In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding='latin1')
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [2]:
import os
os.getcwd()

'C:\\Users\\harin\\evoastra'

In [7]:
df.shape

(180519, 53)

In [8]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [10]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [11]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [13]:
df['Customer Lname'] = df['Customer Lname'].fillna("Unknown")

In [14]:
df['Customer Zipcode'] = df['Customer Zipcode'].fillna(df['Customer Zipcode'].mode()[0])

In [15]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [16]:
df = df.drop_duplicates()

In [17]:
df['order_date_(dateorders)'] = pd.to_datetime(df['order_date_(dateorders)'])
df['shipping_date_(dateorders)'] = pd.to_datetime(df['shipping_date_(dateorders)'])

In [18]:
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   type                           180519 non-null  object
 1   days_for_shipping_(real)       180519 non-null  int64
 2   days_for_shipment_(scheduled)  180519 non-null  int64
 3   benefit_per_order              180519 non-null  float64
 4   sales_per_customer             180519 non-null  float64
 5   delivery_status                180519 non-null  object
 6   late_delivery_risk             180519 non-null  int64
 7   category_id                    180519 non-null  int64
 8   category_name                  180519 non-null  object
 9   customer_city                  180519 non-null  object
 10  customer_country               180519 non-null  object
 11  customer_email                 180519 non-null  object
 12  customer_fname                 180519 non-null  object
 13  customer_id                    180519 non-null  int64
 14  customer_lname                 180519 non-null  object
 15  customer_password              180519 non-null  object
 16  customer_segment               180519 non-null  object
 17  customer_state                 180519 non-null  object
 18  customer_street                180519 non-null  object
 19  customer_zipcode               180519 non-null  float64
 20  department_id                  180519 non-null  int64
 21  department_name                180519 non-null  object
 22  latitude                       180519 non-null  float64
 23  longitude                      180519 non-null  float64
 24  market                         180519 non-null  object
 25  order_city                     180519 non-null  object
 26  order_country                  180519 non-null  object
 27  order_customer_id              180519 non-null  int64
 28  order_date_(dateorders)        180519 non-null  datetime64[ns]
 29  order_id                       180519 non-null  int64
 30  order_item_cardprod_id         180519 non-null  int64
 31  order_item_discount            180519 non-null  float64
 32  order_item_discount_rate       180519 non-null  float64
 33  order_item_id                  180519 non-null  int64
 34  order_item_product_price       180519 non-null  float64
 35  order_item_profit_ratio        180519 non-null  float64
 36  order_item_quantity            180519 non-null  int64
 37  sales                          180519 non-null  float64
 38  order_item_total               180519 non-null  float64
 39  order_profit_per_order         180519 non-null  float64
 40  order_region                   180519 non-null  object
 41  order_state                    180519 non-null  object
 42  order_status                   180519 non-null  object
 43  order_zipcode                  24840 non-null   float64
 44  product_card_id                180519 non-null  int64
 45  product_category_id            180519 non-null  int64
 46  product_description            0 non-null       float64
 47  product_image                  180519 non-null  object
 48  product_name                   180519 non-null  object
 49  product_price                  180519 non-null  float64
 50  product_status                 180519 non-null  int64
 51  shipping_date_(dateorders)     180519 non-null  datetime64[ns]
 52  shipping_mode                  180519 non-null  object
dtypes: datetime64[ns](2), float64(15), int64(14), object(22)
memory usage: 73.0+ MB

In [19]:
df.isnull().sum()

type                                  0
days_for_shipping_(real)              0
days_for_shipment_(scheduled)         0
benefit_per_order                     0
sales_per_customer                    0
delivery_status                       0
late_delivery_risk                    0
category_id                           0
category_name                         0
customer_city                         0
customer_country                      0
customer_email                        0
customer_fname                        0
customer_id                           0
customer_lname                        0
customer_password                     0
customer_segment                      0
customer_state                        0
customer_street                       0
customer_zipcode                      0
department_id                         0
department_name                       0
latitude                              0
longitude                             0
market                                0
order_city                            0
order_country                         0
order_customer_id                     0
order_date_(dateorders)               0
order_id                              0
order_item_cardprod_id                0
order_item_discount                   0
order_item_discount_rate              0
order_item_id                         0
order_item_product_price              0
order_item_profit_ratio               0
order_item_quantity                   0
sales                                 0
order_item_total                      0
order_profit_per_order                0
order_region                          0
order_state                           0
order_status                          0
order_zipcode                    155679
product_card_id                       0
product_category_id                   0
product_description              180519
product_image                         0
product_name                          0
product_price                         0
product_status                        0
shipping_date_(dateorders)            0
shipping_mode                         0
dtype: int64

In [22]:
df = df.drop(columns=['product_description'])

KeyError: "['product_description'] not found in axis"

In [23]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_id', 'category_name', 'customer_city',
       'customer_country', 'customer_email', 'customer_fname', 'customer_id',
       'customer_lname', 'customer_password', 'customer_segment',
       'customer_state', 'customer_street', 'customer_zipcode',
       'department_id', 'department_name', 'latitude', 'longitude', 'market',
       'order_city', 'order_country', 'order_customer_id',
       'order_date_(dateorders)', 'order_id', 'order_item_cardprod_id',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'order_zipcode', 'product_card_id', 'product_category_id',
       'product_image', 'product_name', 'product_price', 'product_status',
       'shipping_date_(dateorders)', 'shipping_mode'],
      dtype='object')

In [24]:
df = df.drop(columns=['order_zipcode'])

In [25]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_id', 'category_name', 'customer_city',
       'customer_country', 'customer_email', 'customer_fname', 'customer_id',
       'customer_lname', 'customer_password', 'customer_segment',
       'customer_state', 'customer_street', 'customer_zipcode',
       'department_id', 'department_name', 'latitude', 'longitude', 'market',
       'order_city', 'order_country', 'order_customer_id',
       'order_date_(dateorders)', 'order_id', 'order_item_cardprod_id',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_card_id', 'product_category_id', 'product_image',
       'product_name', 'product_price', 'product_status',
       'shipping_date_(dateorders)', 'shipping_mode'],
      dtype='object')

In [26]:
df.isnull().sum()

type                             0
days_for_shipping_(real)         0
days_for_shipment_(scheduled)    0
benefit_per_order                0
sales_per_customer               0
delivery_status                  0
late_delivery_risk               0
category_id                      0
category_name                    0
customer_city                    0
customer_country                 0
customer_email                   0
customer_fname                   0
customer_id                      0
customer_lname                   0
customer_password                0
customer_segment                 0
customer_state                   0
customer_street                  0
customer_zipcode                 0
department_id                    0
department_name                  0
latitude                         0
longitude                        0
market                           0
order_city                       0
order_country                    0
order_customer_id                0
order_date_(dateorders)          0
order_id                         0
order_item_cardprod_id           0
order_item_discount              0
order_item_discount_rate         0
order_item_id                    0
order_item_product_price         0
order_item_profit_ratio          0
order_item_quantity              0
sales                            0
order_item_total                 0
order_profit_per_order           0
order_region                     0
order_state                      0
order_status                     0
product_card_id                  0
product_category_id              0
product_image                    0
product_name                     0
product_price                    0
product_status                   0
shipping_date_(dateorders)       0
shipping_mode                    0
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   type                           180519 non-null  object
 1   days_for_shipping_(real)       180519 non-null  int64
 2   days_for_shipment_(scheduled)  180519 non-null  int64
 3   benefit_per_order              180519 non-null  float64
 4   sales_per_customer             180519 non-null  float64
 5   delivery_status                180519 non-null  object
 6   late_delivery_risk             180519 non-null  int64
 7   category_id                    180519 non-null  int64
 8   category_name                  180519 non-null  object
 9   customer_city                  180519 non-null  object
 10  customer_country               180519 non-null  object
 11  customer_email                 180519 non-null  object
 12  customer_fname                 180519 non-null  object
 13  customer_id                    180519 non-null  int64
 14  customer_lname                 180519 non-null  object
 15  customer_password              180519 non-null  object
 16  customer_segment               180519 non-null  object
 17  customer_state                 180519 non-null  object
 18  customer_street                180519 non-null  object
 19  customer_zipcode               180519 non-null  float64
 20  department_id                  180519 non-null  int64
 21  department_name                180519 non-null  object
 22  latitude                       180519 non-null  float64
 23  longitude                      180519 non-null  float64
 24  market                         180519 non-null  object
 25  order_city                     180519 non-null  object
 26  order_country                  180519 non-null  object
 27  order_customer_id              180519 non-null  int64
 28  order_date_(dateorders)        180519 non-null  datetime64[ns]
 29  order_id                       180519 non-null  int64
 30  order_item_cardprod_id         180519 non-null  int64
 31  order_item_discount            180519 non-null  float64
 32  order_item_discount_rate       180519 non-null  float64
 33  order_item_id                  180519 non-null  int64
 34  order_item_product_price       180519 non-null  float64
 35  order_item_profit_ratio        180519 non-null  float64
 36  order_item_quantity            180519 non-null  int64
 37  sales                          180519 non-null  float64
 38  order_item_total               180519 non-null  float64
 39  order_profit_per_order         180519 non-null  float64
 40  order_region                   180519 non-null  object
 41  order_state                    180519 non-null  object
 42  order_status                   180519 non-null  object
 43  product_card_id                180519 non-null  int64
 44  product_category_id            180519 non-null  int64
 45  product_image                  180519 non-null  object
 46  product_name                   180519 non-null  object
 47  product_price                  180519 non-null  float64
 48  product_status                 180519 non-null  int64
 49  shipping_date_(dateorders)     180519 non-null  datetime64[ns]
 50  shipping_mode                  180519 non-null  object
dtypes: datetime64[ns](2), float64(13), int64(14), object(22)
memory usage: 70.2+ MB

In [28]:
df.duplicated().sum()

0

In [29]:
(df['sales'] < 0).sum()

0

In [30]:
(df['order_item_quantity'] <= 0).sum()

0

In [31]:
df['delivery_status'].unique()

array(['Advance shipping', 'Late delivery', 'Shipping on time',
       'Shipping canceled'], dtype=object)

In [32]:
df.shape

(180519, 51)

In [33]:
df.to_csv("cleaned_supplychain_data.csv", index=False)